Blogger\BlogBundle\Entity\User:
    type: entity
    table: simple_users
    repositoryClass: Blogger\BlogBundle\Entity\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            scale: 0
            length: 25
            unique: true
            nullable: false
            precision: 0
        salt:
            type: string
            scale: 0
            length: 32
            unique: false
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: 40
            unique: false
            nullable: false
            precision: 0
        email:
            type: string
            scale: 0
            length: 60
            unique: true
            nullable: false
            precision: 0
        isActive:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: is_active
    lifecycleCallbacks: {  }
